### ISSUE TITLE
Error: Must pass a valid Firebase reference to $firebaseArray (not a string or URL)

### ISSUE THREAD

**Issue by timofeysie** [timofeysie/serene-brushlands#60]
http://trifurcata.cf/#/view3/1
Console log error:
angular.js:12783 Error: Must pass a valid Firebase reference to $firebaseArray (not a string or URL)
    at Object.assertValidRef (http://trifurcata.cf/bower_components/angularfire/dist/angularfire.min.js:12:18756)
    at Object.d (http://trifurcata.cf/bower_components/angularfire/dist/angularfire.min.js:12:4428)
    at d (http://trifurcata.cf/bower_components/angularfire/dist/angularfire.min.js:12:4331)
    at Object.<anonymous> (http://trifurcata.cf/components/factories/inspectionsFactory.js:11:22)
    at Object.invoke (http://trifurcata.cf/bower_components/angular/angular.js:4560:17)
    at Object.enforcedReturnValue [as $get] (http://trifurcata.cf/bower_components/angular/angular.js:4412:37)
    at Object.invoke (http://trifurcata.cf/bower_components/angular/angular.js:4560:17)
    at http://trifurcata.cf/bower_components/angular/angular.js:4377:37
    at getService (http://trifurcata.cf/bower_components/angular/angular.js:4519:39)
    at Object.invoke (http://trifurcata.cf/bower_components/angular/angular.js:4551:13) <div ng-view="" class="ng-scope">(anonymous function) @ angular.js:12783(anonymous function) @ angular.js:9535invokeLinkFn @ angular.js:9081nodeLinkFn @ angular.js:8566compositeLinkFn @ angular.js:7965publicLinkFn @ angular.js:7845boundTranscludeFn @ angular.js:7983controllersBoundTransclude @ angular.js:8593update @ angular-route.js:943$broadcast @ angular.js:16682(anonymous function) @ angular-route.js:627processQueue @ angular.js:15097(anonymous function) @ angular.js:15113$eval @ angular.js:16359$digest @ angular.js:16175$apply @ angular.js:16467done @ angular.js:10852completeRequest @ angular.js:11050requestLoaded @ angular.js:10991
%7B%7BviewModel.imageFile%7D%7D:1 GET http://trifurcata.cf/%7B%7BviewModel.imageFile%7D%7D 404 (Not Found)

**Comment by budhajeewa** [comment]
@timofeysie Please can you close this issue.
